/* Generated by            cobc 2.0.0 */
/* Generated from          tstout.cbl */
/* Generated at            Apr 19 2021 13:43:02 */
/* GNU Cobol build date    Aug 14 2015 18:55:18 */
/* GNU Cobol package date  Mrz 29 2015 14:56:23 UTC */
/* Compile command         /usr/dsg/local/bin/cobc -L /usr/dsg/local/lib -l plib -L/usr/lib/oracle/11.2/client64/lib -locci -lclntsh -lnnz11 -ldl -lm -lpthread -std=mf -use-extfh=FHDSG -xg tstout.cbl */


/* Module path */
static const char		*cob_module_path = NULL;

/* Attributes */

static const cob_field_attr a_1 =	{0x21,   0,   0, 0x0000, NULL};
static const cob_field_attr a_2 =	{0x01,   0,   0, 0x0000, NULL};
static const cob_field_attr a_3 =	{0x12,  10,   0, 0x0001, NULL};


/* Constants */
static const cob_field c_1	= {51, (cob_u8_ptr)"Start:  TSTOUT(tstout - Mon Apr 19 13:43:02 2021).\000", &a_1};
static const cob_field c_2	= {6, (cob_u8_ptr)"TSTOUT", &a_1};
static const cob_field c_3	= {24, (cob_u8_ptr)"Finish: TSTOUT(tstout).\000", &a_1};
static const cob_field c_4	= {35, (cob_u8_ptr)" ABORT - Accessing XOUT. (tstout 2)", &a_1};
static const cob_field c_5	= {17, (cob_u8_ptr)"DBPATH/TSTOUT.rpt", &a_1};


/* Strings */
static const char st_1[]	= "tstout.cbl";
static const char st_2[]	= "PARA-0001-0002";
static const char st_3[]	= "CALL";
static const char st_4[]	= "MOVE";
static const char st_5[]	= "ACCEPT";
static const char st_6[]	= "CONTINUE";
static const char st_7[]	= "PERFORM";
static const char st_8[]	= "ROLLBACK";
static const char st_9[]	= "DISPLAY";
static const char st_10[]	= "STOP RUN";
static const char st_11[]	= "EXITPARA";
static const char st_12[]	= "EXIT";
static const char st_13[]	= "PARA-0002-0001";
static const char st_14[]	= "GO TO";
static const char st_15[]	= "PARA-0002-0002";
static const char st_16[]	= "IF";
static const char st_17[]	= "PARA-0002-0003";
static const char st_18[]	= "PARA-0001-0001";

