/* Generated by            cobc 2.0.0 */
/* Generated from          tstout.cbl */
/* Generated at            Apr 19 2021 13:43:02 */
/* GNU Cobol build date    Aug 14 2015 18:55:18 */
/* GNU Cobol package date  Mrz 29 2015 14:56:23 UTC */
/* Compile command         /usr/dsg/local/bin/cobc -L /usr/dsg/local/lib -l plib -L/usr/lib/oracle/11.2/client64/lib -locci -lclntsh -lnnz11 -ldl -lm -lpthread -std=mf -use-extfh=FHDSG -xg tstout.cbl */

#include <stdio.h>
#include <stdlib.h>
#include <stddef.h>
#include <string.h>
#include <math.h>
#define  COB_KEYWORD_INLINE __inline
#include <libcob.h>

#define  COB_SOURCE_FILE		"tstout.cbl"
#define  COB_PACKAGE_VERSION		"2.0"
#define  COB_PATCH_LEVEL		0
#define  COB_MODULE_FORMATTED_DATE	"Apr 19 2021 13:43:02"
#define  COB_MODULE_DATE		20210419
#define  COB_MODULE_TIME		134302

/* Global variables */
#include "tstout.c.h"

/* Function prototypes */

extern int FHDSG();
static int		TSTOUT ();
static int		TSTOUT_ (const int);

/* Main function */
int
main (int argc, char **argv)
{
  cob_init (argc, argv);
  cob_stop_run (TSTOUT ());
}

/* Functions */

/* PROGRAM-ID 'TSTOUT' */

/* ENTRY 'TSTOUT' */

static int
TSTOUT ()
{
  return TSTOUT_ (0);
}

static int
TSTOUT_ (const int entry)
{
  /* Program local variables */
  #include "tstout.c.l.h"

  /* Start of function code */

  /* CANCEL callback */
  if (unlikely(entry < 0)) {
  	goto P_cancel;
  }

  /* Check initialized, check module allocated, */
  /* set global pointer, */
  /* push module stack, save call parameter count */
  cob_module_enter (&module, &cob_glob_ptr, 0);

  /* Set address of module parameter list */
  module->cob_procedure_params = cob_procedure_params;

  /* Set frame stack pointer */
  frame_ptr = frame_stack;
  frame_ptr->perform_through = 0;
  frame_overflow = frame_ptr + 255 - 1;

  /* Initialize program */
  if (unlikely(initialized == 0)) {
  	goto P_initialize;
  }
  P_ret_initialize:

  /* Increment module active */
  module->module_active++;

  /* Save number of call params */
  module->module_num_params = cob_glob_ptr->cob_call_params;

  /* Entry dispatch */
  goto l_2;

  /* PROCEDURE DIVISION */

  /* Line: 109       : Entry     TSTOUT                  : tstout.cbl */
  l_2:;

  /* Line: 109       : Section   PARA-0001-0002          : tstout.cbl */

  /* Line: 111       : CALL               : tstout.cbl */
  cob_set_location (st_1, 111, st_2, NULL, st_3);
  cob_trace_section ("REMARK", NULL, 0);
  {
    union {
    	unsigned char data[51];
    	cob_s64_t     datall;
    	cob_u64_t     dataull;
    	int           dataint;
    } content_1;

    memcpy (content_1.data, (cob_u8_ptr)"Start:  TSTOUT(tstout - Mon Apr 19 13:43:02 2021).\000", 51);
    cob_procedure_params[0] = (cob_field *)&c_1;
    cob_glob_ptr->cob_call_params = 1;
    if (unlikely(call_REMARK.funcvoid == NULL)) {
      call_REMARK.funcvoid = cob_resolve_cobol ("REMARK", 0, 1);
    }
    b_1 = call_REMARK.funcint (content_1.data);
  }

  /* Line: 114       : MOVE               : tstout.cbl */
  cob_set_location (st_1, 114, st_2, NULL, st_4);
  (*(int *)(b_44 + 4 * 1)) = 8;

  /* Line: 115       : MOVE               : tstout.cbl */
  cob_set_location (st_1, 115, st_2, NULL, st_4);
  (*(int *)(b_44 + 4 * 0)) = 1;

  /* Line: 116       : CALL               : tstout.cbl */
  cob_set_location (st_1, 116, st_2, NULL, st_3);
  cob_trace_section ("DATEMM", NULL, 0);
  cob_procedure_params[0] = &f_44;
  cob_procedure_params[1] = &f_14;
  cob_glob_ptr->cob_call_params = 2;
  if (unlikely(call_DATEMM.funcvoid == NULL)) {
    call_DATEMM.funcvoid = cob_resolve_cobol ("DATEMM", 0, 1);
  }
  b_1 = call_DATEMM.funcint (b_44, b_14);

  /* Line: 117       : ACCEPT             : tstout.cbl */
  cob_set_location (st_1, 117, st_2, NULL, st_5);
  cob_accept_time (&f_15);

  /* Line: 118       : ACCEPT             : tstout.cbl */
  cob_set_location (st_1, 118, st_2, NULL, st_5);
  cob_accept_command_line (&f_19);

  /* Line: 119       : CONTINUE           : tstout.cbl */
  cob_set_location (st_1, 119, st_2, NULL, st_6);
  ;

  /* Line: 120       : PERFORM            : tstout.cbl */
  cob_set_location (st_1, 120, st_2, NULL, st_7);
  /* PERFORM PARA-0002-0002 */
  frame_ptr++;
  if (unlikely(frame_ptr == frame_overflow))
      cob_fatal_error (COB_FERROR_STACK);
  frame_ptr->perform_through = 9;
  frame_ptr->return_address_ptr = &&l_18;
  goto l_9;
  l_18:
  frame_ptr--;

  /* Line: 121       : ROLLBACK           : tstout.cbl */
  cob_set_location (st_1, 121, st_2, NULL, st_8);
  cob_extfh_rollback (FHDSG, h_XOUT_FILE);

  /* Line: 122       : DISPLAY            : tstout.cbl */
  cob_set_location (st_1, 122, st_2, NULL, st_9);
  cob_display (0, 1, 1, &c_2);

  /* Line: 123       : PERFORM            : tstout.cbl */
  cob_set_location (st_1, 123, st_2, NULL, st_7);
  /* PERFORM PARA-0002-0003 */
  frame_ptr++;
  if (unlikely(frame_ptr == frame_overflow))
      cob_fatal_error (COB_FERROR_STACK);
  frame_ptr->perform_through = 12;
  frame_ptr->return_address_ptr = &&l_19;
  goto l_12;
  l_19:
  frame_ptr--;

  /* Line: 124       : CALL               : tstout.cbl */
  cob_set_location (st_1, 124, st_2, NULL, st_3);
  cob_trace_section ("REMARK", NULL, 0);
  {
    union {
    	unsigned char data[24];
    	cob_s64_t     datall;
    	cob_u64_t     dataull;
    	int           dataint;
    } content_1;

    memcpy (content_1.data, (cob_u8_ptr)"Finish: TSTOUT(tstout).\000", 24);
    cob_procedure_params[0] = (cob_field *)&c_3;
    cob_glob_ptr->cob_call_params = 1;
    if (unlikely(call_REMARK.funcvoid == NULL)) {
      call_REMARK.funcvoid = cob_resolve_cobol ("REMARK", 0, 1);
    }
    b_1 = call_REMARK.funcint (content_1.data);
  }

  /* Line: 126       : STOP RUN           : tstout.cbl */
  cob_set_location (st_1, 126, st_2, NULL, st_10);
  cob_stop_run (b_1);

  /* Line: 128       : Paragraph EXITPARA                : tstout.cbl */

  /* Line: 129       : EXIT               : tstout.cbl */
  cob_set_location (st_1, 129, st_2, st_11, st_12);

  /* Line: 131       : Section   PARA-0002-0001          : tstout.cbl */

  /* Line: 133       : GO TO              : tstout.cbl */
  cob_set_location (st_1, 133, st_13, NULL, st_14);
  goto l_8;

  /* Line: 135       : Paragraph EXITPARA                : tstout.cbl */
  l_8:;

  /* Line: 136       : EXIT               : tstout.cbl */
  cob_set_location (st_1, 136, st_13, st_11, st_12);

  /* Line: 138       : Section   PARA-0002-0002          : tstout.cbl */
  l_9:;

  /* Line: 140       : CALL               : tstout.cbl */
  cob_set_location (st_1, 140, st_15, NULL, st_3);
  cob_trace_section ("INITX", NULL, 0);
  cob_procedure_params[0] = NULL;
  cob_procedure_params[1] = &f_49;
  cob_glob_ptr->cob_call_params = 2;
  if (unlikely(call_INITX.funcvoid == NULL)) {
    call_INITX.funcvoid = cob_resolve_cobol ("INITX", 0, 1);
  }
  b_1 = call_INITX.funcint (h_XOUT_FILE, b_49);

  /* Line: 142       : IF                 : tstout.cbl */
  cob_set_location (st_1, 142, st_15, NULL, st_16);
  if (((int)memcmp (b_49 + 4, (cob_u8_ptr)"30", 2) == 0))
  {

    /* Line: 143       : PERFORM            : tstout.cbl */
    cob_set_location (st_1, 143, st_15, NULL, st_7);
    /* PERFORM PARA-0002-0003 */
    frame_ptr++;
    if (unlikely(frame_ptr == frame_overflow))
        cob_fatal_error (COB_FERROR_STACK);
    frame_ptr->perform_through = 12;
    frame_ptr->return_address_ptr = &&l_20;
    goto l_12;
    l_20:
    frame_ptr--;

    /* Line: 144       : CALL               : tstout.cbl */
    cob_set_location (st_1, 144, st_15, NULL, st_3);
    cob_trace_section ("REMARK", NULL, 0);
    {
      union {
      	unsigned char data[24];
      	cob_s64_t     datall;
      	cob_u64_t     dataull;
      	int           dataint;
      } content_1;

      memcpy (content_1.data, (cob_u8_ptr)"Finish: TSTOUT(tstout).\000", 24);
      cob_procedure_params[0] = (cob_field *)&c_3;
      cob_glob_ptr->cob_call_params = 1;
      if (unlikely(call_REMARK.funcvoid == NULL)) {
        call_REMARK.funcvoid = cob_resolve_cobol ("REMARK", 0, 1);
      }
      b_1 = call_REMARK.funcint (content_1.data);
    }

    /* Line: 146       : MOVE               : tstout.cbl */
    cob_set_location (st_1, 146, st_15, NULL, st_4);
    (*(int *)(b_44 + 4 * 1)) = 35;

    /* Line: 147       : MOVE               : tstout.cbl */
    cob_set_location (st_1, 147, st_15, NULL, st_4);
    (*(int *)(b_44 + 4 * 2)) = 2;

    /* Line: 148       : MOVE               : tstout.cbl */
    cob_set_location (st_1, 148, st_15, NULL, st_4);
    (*(int *)(b_44 + 4 * 0)) = 2;

    /* Line: 149       : CALL               : tstout.cbl */
    cob_set_location (st_1, 149, st_15, NULL, st_3);
    cob_trace_section ("ABORT", NULL, 0);
    cob_procedure_params[0] = &f_44;
    cob_procedure_params[1] = (cob_field *)&c_4;
    cob_procedure_params[2] = &f_51;
    cob_glob_ptr->cob_call_params = 3;
    if (unlikely(call_ABORT.funcvoid == NULL)) {
      call_ABORT.funcvoid = cob_resolve_cobol ("ABORT", 0, 1);
    }
    b_1 = call_ABORT.funcint (b_44, (cob_u8_ptr)" ABORT - Accessing XOUT. (tstout 2)", b_49 + 4);
  }

  /* Line: 153       : Paragraph EXITPARA                : tstout.cbl */

  /* Line: 154       : EXIT               : tstout.cbl */
  cob_set_location (st_1, 154, st_15, st_11, st_12);

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 9)
    goto *frame_ptr->return_address_ptr;

  /* Line: 156       : Section   PARA-0002-0003          : tstout.cbl */
  l_12:;

  /* Line: 158       : CALL               : tstout.cbl */
  cob_set_location (st_1, 158, st_17, NULL, st_3);
  cob_trace_section ("ENDWIN", NULL, 0);
  cob_glob_ptr->cob_call_params = 0;
  if (unlikely(call_ENDWIN.funcvoid == NULL)) {
    call_ENDWIN.funcvoid = cob_resolve_cobol ("ENDWIN", 0, 1);
  }
  b_1 = call_ENDWIN.funcint ();

  /* Line: 160       : ROLLBACK           : tstout.cbl */
  cob_set_location (st_1, 160, st_17, NULL, st_8);
  cob_extfh_rollback (FHDSG, h_XOUT_FILE);

  /* Line: 162       : CALL               : tstout.cbl */
  cob_set_location (st_1, 162, st_17, NULL, st_3);
  cob_trace_section ("CLOSR", NULL, 0);
  cob_procedure_params[0] = NULL;
  cob_procedure_params[1] = &f_49;
  cob_glob_ptr->cob_call_params = 2;
  if (unlikely(call_CLOSR.funcvoid == NULL)) {
    call_CLOSR.funcvoid = cob_resolve_cobol ("CLOSR", 0, 1);
  }
  b_1 = call_CLOSR.funcint (h_XOUT_FILE, b_49);

  /* Line: 165       : Paragraph EXITPARA                : tstout.cbl */

  /* Line: 166       : EXIT               : tstout.cbl */
  cob_set_location (st_1, 166, st_17, st_11, st_12);

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 12)
    goto *frame_ptr->return_address_ptr;

  /* Line: 168       : Section   PARA-0001-0001          : tstout.cbl */

  /* Line: 170       : GO TO              : tstout.cbl */
  cob_set_location (st_1, 170, st_18, NULL, st_14);
  goto l_17;

  /* Line: 172       : Paragraph EXITPARA                : tstout.cbl */
  l_17:;

  /* Line: 173       : EXIT               : tstout.cbl */
  cob_set_location (st_1, 173, st_18, st_11, st_12);

  /* Program exit */

  /* Decrement module active count */
  if (module->module_active) {
  	module->module_active--;
  }

  /* Pop module stack */
  cob_module_leave (module);

  /* Program return */
  return b_1;


  /* Paragraph Default Error Handler   */
  l_1:;

  if (!(cob_glob_ptr->cob_error_file->flag_select_features & COB_SELECT_FILE_STATUS)) {
  	cob_fatal_error (COB_FERROR_FILE);
  }

  /* Implicit Default Error Handler return */
  if (frame_ptr->perform_through == 1)
    goto *frame_ptr->return_address_ptr;

  /* Fatal error if reached */
  cob_fatal_error (COB_FERROR_CODEGEN);


  /* Program initialization */
  P_initialize:

  cob_check_version (COB_SOURCE_FILE, COB_PACKAGE_VERSION, COB_PATCH_LEVEL);

  cob_module_path = cob_glob_ptr->cob_main_argv0;

  /* Initialize module structure */
  module->module_name = "TSTOUT";
  module->module_formatted_date = COB_MODULE_FORMATTED_DATE;
  module->module_source = COB_SOURCE_FILE;
  module->module_entry.funcptr = (void *(*)())TSTOUT;
  module->module_cancel.funcptr = (void *(*)())TSTOUT_;
  module->collating_sequence = NULL;
  module->crt_status = NULL;
  module->cursor_pos = NULL;
  module->module_ref_count = NULL;
  module->module_path = &cob_module_path;
  module->module_active = 0;
  module->module_date = COB_MODULE_DATE;
  module->module_time = COB_MODULE_TIME;
  module->module_type = 0;
  module->module_param_cnt = 0;
  module->module_returning = 0;
  module->ebcdic_sign = 0;
  module->decimal_point = '.';
  module->currency_symbol = '$';
  module->numeric_separator = ',';
  module->flag_filename_mapping = 1;
  module->flag_binary_truncate = 0;
  module->flag_pretty_display = 0;
  module->flag_host_sign = 0;
  module->flag_no_phys_canc = 1;
  module->flag_main = 1;
  module->flag_fold_call = 0;
  module->flag_exit_program = 0;

  /* Initialize cancel callback */
  cob_set_cancel (module);

  /* Initialize WORKING-STORAGE */
  b_1 = 0;
  memcpy (b_9, "00000001", 8);
  memcpy (b_10, "(C) DIGITAL SYSTEMS GROUP, INC. 1991-2017 IPL", 45);
  memset (b_10 + 45, 32, 5);
  memcpy (b_11, "Mon Apr 19 13:43:02 2021", 24);
  memset (b_11 + 24, 32, 6);
  memcpy (b_12, "v3.0.0g", 7);
  memset (b_12 + 7, 32, 3);
  memcpy (b_13, "Wed Sep 26 16:29:21 EDT 2018  ", 30);
  memset (b_14, 32, 8);
  memset (b_15, 48, 6);
  memset (b_16, 32, 8);
  memset (b_17, 48, 6);
  memset (b_18, 0, 5);
  memset (b_19, 32, 20);
  memset (b_19 + 20, 32, 7);
  memset (b_19 + 27, 32, 7);
  memset (b_19 + 34, 32, 4);
  memset (b_19 + 38, 32, 5132);
  (*(int *)(b_25)) = 2;
  (*(int *)(b_26)) = 0;
  (*(int *)(b_26 + 4)) = 0;
  (*(int *)(b_26 + 8)) = 0;
  (*(int *)(b_30)) = 0;
  (*(int *)(b_30 + 4)) = 0;
  cob_set_packed_zero (COB_SET_FLD(f0, 6, b_30 + 8, &a_3));
  memset (b_30 + 14, 32, 30);
  memset (b_35, 48, 8);
  memset (b_36, 0, 5);
  memset (b_37, 32, 10);
  memset (b_38, 0, 5);
  memset (b_39, 0, 5);
  memset (b_40, 0, 5);
  memset (b_41, 32, 2);
  memset (b_42, 0, 5);
  memset (b_43, 0, 2);
  memset (b_44, 48, 36);
  memset (b_46, 48, 36);
  memcpy (b_48, "TSTOUT", 6);
  memset (b_48 + 6, 32, 4);
  memcpy (b_49, "XOUT", 4);
  *(cob_u8_ptr)(b_49 + 4) = 32;
  *(cob_u8_ptr)(b_49 + 5) = 32;
  memset (b_49 + 6, 32, 2);
  *(cob_u8_ptr)(b_49 + 8) = 70;
  *(cob_u8_ptr)(b_49 + 9) = 70;
  memcpy (b_49 + 10, "TSTOUT.rpt", 10);
  memset (b_49 + 20, 32, 10);
  memset (b_49 + 30, 32, 10);
  memset (b_49 + 40, 32, 10);
  memset (b_49 + 50, 32, 4);
  *(cob_u8_ptr)(b_49 + 54) = 50;
  *(cob_u8_ptr)(b_49 + 55) = 48;
  *(cob_u8_ptr)(b_49 + 56) = 48;
  *(cob_u8_ptr)(b_49 + 57) = 48;
  memcpy (b_74, "00000001", 8);


  if (!h_XOUT_FILE)
  {
    h_XOUT_FILE = cob_cache_malloc (sizeof(cob_file)+20);
  }
  h_XOUT_FILE->select_name = (const char *)"XOUT-FILE";
  h_XOUT_FILE->file_status = h_XOUT_FILE_status;
  memset (h_XOUT_FILE_status, '0', 2);
  h_XOUT_FILE->assign = (cob_field *)&c_5;
  h_XOUT_FILE->record = &f_8;
  h_XOUT_FILE->variable_record = NULL;
  h_XOUT_FILE->record_min = 2;
  h_XOUT_FILE->record_max = 2;
  h_XOUT_FILE->nkeys = 0;
  h_XOUT_FILE->keys = NULL;
  h_XOUT_FILE->file = NULL;
  h_XOUT_FILE->fd = -1;
  h_XOUT_FILE->organization = 0;
  h_XOUT_FILE->access_mode = 1;
  h_XOUT_FILE->lock_mode = 0;
  h_XOUT_FILE->open_mode = 0;
  h_XOUT_FILE->flag_optional = 0;
  h_XOUT_FILE->flag_line_adv = 0;
  h_XOUT_FILE->last_open_mode = 0;
  h_XOUT_FILE->flag_operation = 0;
  h_XOUT_FILE->flag_nonexistent = 0;
  h_XOUT_FILE->flag_end_of_file = 0;
  h_XOUT_FILE->flag_begin_of_file = 0;
  h_XOUT_FILE->flag_first_read = 0;
  h_XOUT_FILE->flag_read_done = 0;
  h_XOUT_FILE->flag_select_features = 0;
  h_XOUT_FILE->flag_needs_nl = 0;
  h_XOUT_FILE->flag_needs_top = 0;
  h_XOUT_FILE->file_version = 2;
  h_XOUT_FILE->file_format = 255;
  h_XOUT_FILE->file_features = 0;

  initialized = 1;
  goto P_ret_initialize;

  /* CANCEL callback handling */
  P_cancel:

  if (!initialized) {
  	return 0;
  }
  if (module->module_active) {
  	cob_fatal_error (COB_FERROR_CANCEL);
  }

  initialized = 0;
  return 0;

}

/* End PROGRAM-ID 'TSTOUT' */

/* End functions */

